export const GET_KERANJANG_REQUEST = "GET_KERANJANG_REQUEST";
export const GET_KERANJANG_SUCCESS = "GET_KERANJANG_SUCCESS";
export const GET_KERANJANG_FAILED = "GET_KERANJANG_FAILED";

export const TOTAL_KERANJANG_REQUEST = "TOTAL_KERANJANG_REQUEST";
export const TOTAL_KERANJANG_SUCCESS = "TOTAL_KERANJANG_SUCCESS";
export const TOTAL_KERANJANG_FAILED = "TOTAL_KERANJANG_FAILED";
