export const GET_KERANJANG_REQUEST = "GET_KERANJANG_REQUEST";
export const GET_KERANJANG_SUCCESS = "GET_KERANJANG_SUCCESS";
export const GET_KERANJANG_FAILED = "GET_KERANJANG_FAILED";

export const GET_ONE_KERANJANG_REQUEST = "GET_ONE_KERANJANG_REQUEST";
export const GET_ONE_KERANJANG_SUCCESS = "GET_ONE_KERANJANG_SUCCESS";
export const GET_ONE_KERANJANG_FAILED = "GET_ONE_KERANJANG_FAILED";

export const EDIT_KERANJANG_REQUEST = "EDIT_KERANJANG_REQUEST";
export const EDIT_KERANJANG_SUCCESS = "EDIT_KERANJANG_SUCCESS";
export const EDIT_KERANJANG_FAILED = "EDIT_KERANJANG_FAILED";
